name: "ArgoCD Application Sync Action (allow insecure)"
description: "Sync your ArgoCD application from GitHub"
author: "rekruti"
inputs:
  address:
    description: "ArgoCD server address"
    required: true
  token:
    description: "ArgoCD token"
    required: true
  appName:
    description: "Application name to sync"
    required: true
  insecure:
    description: "Whether server is insecure"
    required: true
  imageTag:
    description: "Set parameter: image.tag"
    required: true

runs:
  using: "docker"
  image: "docker://rekruti/argocd-actions:v1.1.1"
